name: Capybara generate

on: [workflow_dispatch, push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash -el {0}  

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Set up enviroment
      run: |
        pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu116
        pip install sdkit

    - name: Create image
      run: |
        python genImg.py
        
    - name: Upload images
      uses: actions/upload-artifact@v4
      with:
        name: 'Images'
        path: './tmpImages'