name: Generate images

on: 
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */3 * * *'  # Repeat every 3h

jobs:
  image:
    runs-on: ubuntu-latest

    env:
      python: 3.11

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python }}
        
    - name: Run generator scripts
      run: |
        sh scripts/install.sh
        python scripts/genImg.py
        mv tmpImages/image_0.jpeg tmpImages/$(date '+%Y%m%d%H%M%S').jpeg

    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
        name: capybara
        path: ./tmpImages

    - name: Push new image
      run: |
        mkdir -p ./images/capy/
        cp tmpImages/*.jpeg ./images/capy/
        rm -rf tmpImages
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git add .
        git commit -m "Photo $(date '+%Y%m%d%H%M%S')"
        git push