name: Generate images

on: [workflow_dispatch, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
        
    - name: Run generator scripts
      run: |
        cd .github/workflows/scripts
        sh install.sh
        python genImg.py
        
    - name: Upload images
      uses: actions/upload-artifact@v4
      with:
        name: 'Images'
        path: './tmpImages'