name: Generate images

on: 
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */3 * * *'  # Repeat every 3h

jobs:
  prompt:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Run prompt generator scripts
      working-directory: scripts
      run: |
        export CONFIGPATH=config
        sh prompt.sh

    - name: Upload prompt
      uses: actions/upload-artifact@v4
      with:
        name: prompt
        path: scripts/prompt.txt


  image:
    strategy:
      matrix:
        model: [
          sd_xl_turbo_1.0_fp16.safetensors, 
          v2-1_768-ema-pruned.safetensors,
          v1-5-pruned-emaonly.safetensors
        ]
    runs-on: ubuntu-latest
    needs: prompt

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        
    - name: Download prompt
      uses: actions/download-artifact@v4
      with:
        name: prompt
        path: scripts

    - name: Config & run generator
      working-directory: scripts
      run: |
        export CONFIGPATH=config
        export MATRIXMODEL=${{ matrix.model }}
        export JOBINDEX=${{ strategy.job-index }}
        sh image.sh   

    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
        name: capybara-${{ strategy.job-index }}
        path: scripts/tmp/image


  push:
    runs-on: ubuntu-latest
    needs: image

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with: 
        persist-credentials: false
        fetch-depth: 0

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: scripts/tmp

    - name: Cleanup repository
      working-directory: scripts
      run: |
        export CONFIGPATH=config
        sh push.sh  

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        force: true
