name: Capybara generate

on: [workflow_dispatch, push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash -el {0}  

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Clone StableDiffusion
      uses: actions/checkout@v4
      with:
        repository: 'Stability-AI/stablediffusion'
        fetch-depth: 2
        path: 'StableDiffusion'

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: ldm
        environment-file: StableDiffusion/environment.yaml

    - name: Set up enviroment
      run: |
        cd StableDiffusion
        conda install pytorch==1.12.1 torchvision==0.13.1 -c pytorch
        pip install transformers==4.19.2 diffusers invisible-watermark
        pip install -e .
        wget -O "SD2.1-v.ckpt" https://huggingface.co/stabilityai/stable-diffusion-2-1/resolve/main/v2-1_768-ema-pruned.ckpt

    - name: Create image
      run: |
        cd StableDiffusion
        python scripts/txt2img.py --prompt "very proffesional capybara photo" --ckpt "SD2.1-v.ckpt" --config "configs/stable-diffusion/v2-inference-v.yaml" --H 768 --W 768  

        ls
        
    - name: (?) Push files
      run: |
        cd StableDiffusion
        ls
        
