name: Generate images

on: 
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */3 * * *'  # Repeat every 3h

jobs:
  prompt:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Run prompt generator scripts
      id: set_variable
      run: |
        export CONFIGPATH = .github/workflows/scripts/config
        sh .github/workflows/scripts/prompt.sh

    - name: Upload prompt
      uses: actions/upload-artifact@v4
      with:
        name: prompt
        path: ~/prompt.txt




  image:
    strategy:
      matrix:
        model: [
          sd_xl_turbo_1.0, 
          v2-1_768,
          v1-5
        ]
    runs-on: ubuntu-latest
    needs: prompt

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        
    - name: Download prompt
      uses: actions/download-artifact@v4
      with:
        name: prompt
        path: ~/

    - name: Config & run generator
      run: |
        export CONFIGPATH = .github/workflows/scripts/config
        export MATRIXMODEL = ${{ matrix.model }}
        export JOBINDEX = ${{ strategy.job-index }}
        sh .github/workflows/scripts/image.sh   

    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
        name: capybara-${{ strategy.job-index }}
        path: ~/tmp/image


  push:
    runs-on: ubuntu-latest
    needs: image

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with: 
        persist-credentials: false
        fetch-depth: 0

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ~/tmp

    - name: Cleanup repository
      run: |
        export CONFIGPATH = .github/workflows/scripts/config
        sh .github/workflows/scripts/push.sh  

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        force: true