name: Generate images

on: 
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */3 * * *'  # Repeat every 3h

jobs:
  image:
    env:
      python: 3.11

    strategy:
      matrix:
        model: [
          sd_xl_turbo_1.0, 
          v2-1_768,
          v1-5
        ]

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python }}
        
    - name: Run generator scripts
      run: |
        sh scripts/install.sh
        python scripts/genPrompts.py
        python scripts/genImg.py scripts/config ${{ matrix.model }}
        mv tmp/images/image_0.jpeg tmp/images/$(date '+%Y%m%d%H%M%S')-${{ strategy.job-index }}.jpeg

    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
        name: capybara-${{ strategy.job-index }}
        path: ./tmp/images


  push:
    runs-on: ubuntu-latest
    needs: image
    steps:

    - name: Clone repository
      uses: actions/checkout@v4
      with: 
        persist-credentials: false
        fetch-depth: 0

    - name: Download images from artifacts
      uses: actions/download-artifact@v4
      with:
        path: tmp

    - name: Push new images
      run: |
        mkdir -p ./images/capy/
        cp out/*/*.jpeg ./data/images/capy/
        rm -rf out
        git config --global user.name image-gen
        git config --global user.email github-actions@github.com
        git add .
        git commit -m "Next capy photos"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        force: true