name: Generate images

on: 
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */3 * * *'  # Repeat every 3h

jobs:
  image:
    runs-on: ubuntu-latest

    env:
      python: 3.11

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with: 
        persist-credentials: false
        fetch-depth: 0

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python }}
        
    - name: Run generator scripts
      run: |
        sh scripts/install.sh
        python scripts/genImg.py scripts/prompts.json
        mv tmp/images/image_0.jpeg tmp/images/$(date '+%Y%m%d%H%M%S').jpeg

    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
        name: capybara
        path: ./tmp/images

    - name: Push new image
      run: |
        mkdir -p ./images/capy/
        cp tmp/images/*.jpeg ./images/capy/
        rm -rf tmp
        git config --global user.name image-gen
        git config --global user.email github-actions@github.com
        git add .
        git commit -m "Next capy photo"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        force: true